version: '3.7'

services:
  db:
    image: mysql:8.0.32
    container_name: db
    hostname: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: marketplace
    ports:
      - '33066:3306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db: